name: Publish site
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "app/**"
      - ".github/workflows/app.yaml"

env:
  API_URL: api.warshop.io
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_REGION: us-east-1
  CLERK_API_KEY: ${{ secrets.CLERK_API_KEY }}
  CLERK_FRONTEND_API: clerk.warshop.io
  DATABASE_URL: mysql://warshop_io:${{ secrets.MYSQL_PASSWORD }}@vargas-arts.c2sjnb5f4d57.us-east-1.rds.amazonaws.com:5432/washop_io
  IS_PRODUCTION: 1
  ORIGIN: https://warshop.io
  STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: deploy
        run: npm run deploy
